[package]
name = "guest-logistic-regression"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "2.3.1", default-features = false, features = ["std"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }