#![no_main]
#![no_std]

use risc0_zkvm::guest::env;

risc0_zkvm::guest::entry!(main);

// Fixed-point arithmetic scale factor (4 decimal places)
const SCALE: i64 = 10000;

fn main() {
    // Read session context first (for MCP session binding)
    let session_id: [u8; 16] = env::read();
    let request_nonce: u64 = env::read();
    
    // Read two fixed-point numbers (scaled integers) from the host
    let a: i64 = env::read();
    let b: i64 = env::read();
    
    // Perform addition (fixed-point addition is just regular addition)
    let result = a + b;
    
    // Commit session context first (proves this was generated by MCP server)
    env::commit(&session_id);
    env::commit(&request_nonce);
    
    // Commit the original inputs and result to the journal for verification
    env::commit(&a);
    env::commit(&b);
    env::commit(&result);
}
