[workspace]
resolver = "2"
members = ["host", "methods", "verify", "methods/guest-multiply", "methods/guest-sqrt", "methods/guest-modexp"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
